# Generated by Django 6.0 on 2025-12-04 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text="Titre de l'enregistrement", max_length=255)),
                ('type', models.CharField(choices=[('antenne', 'Antenne'), ('emission', 'Émission'), ('reunion', 'Réunion')], default='antenne', max_length=20)),
                ('custom_name', models.CharField(blank=True, help_text='Nom personnalisé du fichier', max_length=255)),
                ('file', models.FileField(help_text='Fichier audio', upload_to='recordings/')),
                ('format', models.CharField(choices=[('mp3', 'MP3'), ('wav', 'WAV'), ('ogg', 'OGG'), ('m4a', 'M4A'), ('flac', 'FLAC'), ('webm', 'WebM')], default='mp3', max_length=10)),
                ('sample_rate', models.IntegerField(default=44100, help_text="Taux d'échantillonnage (Hz)")),
                ('duration_seconds', models.FloatField(default=0.0, help_text='Durée en secondes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retained_until', models.DateTimeField(blank=True, help_text="Date d'expiration automatique", null=True)),
                ('transcript', models.TextField(blank=True, help_text='Transcription du texte')),
                ('summary', models.TextField(blank=True, help_text='Résumé généré par IA')),
                ('vad_report', models.JSONField(blank=True, default=dict, help_text='Rapport de détection de voix (VAD)')),
                ('flagged', models.BooleanField(default=False, help_text='Marqué pour révision (blancs détectés, etc.)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='recordings__created_0ddc66_idx'), models.Index(fields=['type'], name='recordings__type_bcebda_idx'), models.Index(fields=['flagged'], name='recordings__flagged_28788e_idx')],
            },
        ),
    ]
