# Generated by Django 6.0 on 2025-12-04 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_text', models.TextField()),
                ('summary_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detail_level', models.CharField(default='medium', max_length=20)),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcription_history', to='recordings.recording')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_path', models.CharField(default='recordings/', help_text='Chemin de stockage personnalisé', max_length=500)),
                ('default_format', models.CharField(choices=[('mp3', 'MP3'), ('wav', 'WAV'), ('ogg', 'OGG'), ('flac', 'FLAC'), ('webm', 'WebM')], default='mp3', max_length=10)),
                ('default_quality', models.CharField(choices=[('high', 'Haute'), ('medium', 'Moyenne'), ('low', 'Basse')], default='high', max_length=10)),
                ('default_sample_rate', models.IntegerField(default=44100)),
                ('default_channels', models.IntegerField(choices=[(1, 'Mono'), (2, 'Stéréo')], default=2)),
                ('auto_split_enabled', models.BooleanField(default=False)),
                ('auto_split_duration_minutes', models.IntegerField(default=60, help_text='Durée avant découpage automatique (minutes)')),
                ('retention_days', models.IntegerField(default=30, help_text='Durée de rétention en jours')),
                ('naming_template', models.CharField(default='{type}-{date}-{time}', help_text='Template: {type}, {date}, {time}, {timestamp}, {jour}, {mois}, {heure}, {minutes}', max_length=255)),
                ('vad_sensitivity', models.IntegerField(default=2, help_text='Sensibilité VAD (0-3)')),
                ('silence_threshold_seconds', models.FloatField(default=5.0, help_text='Seuil minimal pour silence anormal (secondes)')),
                ('email_alerts_enabled', models.BooleanField(default=False)),
                ('email_host', models.CharField(blank=True, max_length=255)),
                ('email_port', models.IntegerField(default=587)),
                ('email_user', models.CharField(blank=True, max_length=255)),
                ('email_password', models.CharField(blank=True, max_length=255)),
                ('transcription_enabled', models.BooleanField(default=False)),
                ('summary_enabled', models.BooleanField(default=False)),
                ('summary_detail_level', models.CharField(choices=[('brief', 'Bref'), ('medium', 'Moyen'), ('detailed', 'Détaillé')], default='medium', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
