# Generated by Django 4.2.27 on 2025-12-05 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_transcriptionhistory_usersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='transcript',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='summary_detail_level',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='summary_enabled',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='transcription_enabled',
        ),
        migrations.DeleteModel(
            name='TranscriptionHistory',
        ),
    ]
