# Generated by Django 6.0 on 2025-12-05 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0003_remove_recording_summary_remove_recording_transcript_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'Paramètres utilisateur', 'verbose_name_plural': 'Paramètres utilisateurs'},
        ),
    ]
